### ISSUE TITLE
Default behaviours

### ISSUE THREAD

**Issue by peterbrendel** [intpsnobs/ga#1]
Poderíamos manter comportamentos padrões para algumas manipulações de dados.

e.g.
```python
def show_population(pop : list, *args):
    default_show_list(pop)
    for arg in args:
        arg(pop)
```

Não sei se ficaria bom de usar, mas pode ser util pra separar diferentes prints, o default printa a populacao, e cada arg pode printar, por exemplo, um board customizado, a lista ordenada, ou executar qualquer tipo de visualizacao.

e.g.
```python
show_population(population, board_view, sorted_view, plot_view)
```

**Comment by RicardoStoklosa** [comment]
Foi colocado o parametro callable opcional fenotype, onde recebe um individuo e imprime no arquivo de saida apos os prints obrigatorios. Acho que uma funcao é o suficiente ja que vc pode retornar uma string com o tamanho indeterminado.
